/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'resolved' : boolean,
  'alertType' : string,
  'patientId' : bigint,
  'createdAt' : Timestamp,
  'message' : string,
  'recordId' : bigint,
}
export interface HealthRecord {
  'id' : bigint,
  'bpSystolic' : bigint,
  'patientId' : bigint,
  'temperature' : number,
  'createdAt' : Timestamp,
  'spo2' : bigint,
  'visitType' : string,
  'reviewedBy' : UserId,
  'glucose' : bigint,
  'volunteerId' : UserId,
  'checkDate' : string,
  'heartRate' : bigint,
  'doctorAdvice' : string,
  'symptoms' : string,
  'bpDiastolic' : bigint,
  'reviewed' : boolean,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'volunteerId' : UserId,
  'address' : string,
  'village' : string,
  'gender' : string,
  'notes' : string,
  'patientCode' : string,
  'phone' : string,
  'condition' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'principal' : Principal,
  'patientId' : [] | [bigint],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserId = bigint;
export type UserRole = { 'patient' : null } |
  { 'admin' : null } |
  { 'doctor' : null } |
  { 'volunteer' : null };
export interface _SERVICE {
  'createPatient' : ActorMethod<
    [string, bigint, string, string, string, string, string, bigint, string],
    Patient
  >,
  'createRecord' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      number,
      string,
      string,
    ],
    { 'alerts' : Array<Alert>, 'record' : HealthRecord }
  >,
  'createUser' : ActorMethod<[string, string, UserRole], User>,
  'getAlerts' : ActorMethod<
    [],
    Array<
      {
        'alert' : Alert,
        'village' : string,
        'patientCode' : string,
        'patientName' : string,
      }
    >
  >,
  'getCurrentUser' : ActorMethod<[], [] | [User]>,
  'getMyAlerts' : ActorMethod<
    [],
    Array<
      {
        'alert' : Alert,
        'village' : string,
        'patientCode' : string,
        'patientName' : string,
      }
    >
  >,
  'getMyRecord' : ActorMethod<
    [],
    [] | [
      {
        'patient' : Patient,
        'volunteerName' : string,
        'records' : Array<HealthRecord>,
      }
    ]
  >,
  'getPatient' : ActorMethod<
    [bigint],
    [] | [
      {
        'patient' : Patient,
        'volunteerName' : string,
        'records' : Array<HealthRecord>,
      }
    ]
  >,
  'getPatients' : ActorMethod<
    [],
    Array<
      {
        'patient' : Patient,
        'volunteerName' : string,
        'lastCheck' : [] | [string],
      }
    >
  >,
  'getRecords' : ActorMethod<
    [[] | [boolean], [] | [bigint]],
    Array<
      {
        'village' : string,
        'patientCode' : string,
        'patientName' : string,
        'record' : HealthRecord,
      }
    >
  >,
  'getStats' : ActorMethod<
    [],
    {
      'pendingReview' : bigint,
      'totalPatients' : bigint,
      'activeVolunteers' : bigint,
      'recordsToday' : bigint,
      'activeAlerts' : bigint,
      'totalRecords' : bigint,
      'alertPatients' : bigint,
    }
  >,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getVolunteers' : ActorMethod<[], Array<User>>,
  'linkPatientAccount' : ActorMethod<[bigint, bigint], [] | [User]>,
  'registerUser' : ActorMethod<[string, string, UserRole], User>,
  'resolveAlert' : ActorMethod<[bigint], [] | [Alert]>,
  'reviewRecord' : ActorMethod<[bigint, string], [] | [HealthRecord]>,
  'seedDemoData' : ActorMethod<[], string>,
  'updatePatient' : ActorMethod<
    [bigint, string, string, string],
    [] | [Patient]
  >,
  'updateUserRole' : ActorMethod<[bigint, UserRole], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];