/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const UserId = IDL.Nat;
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'volunteerId' : UserId,
  'address' : IDL.Text,
  'village' : IDL.Text,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'patientCode' : IDL.Text,
  'phone' : IDL.Text,
  'condition' : IDL.Text,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'alertType' : IDL.Text,
  'patientId' : IDL.Nat,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'recordId' : IDL.Nat,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Nat,
  'bpSystolic' : IDL.Nat,
  'patientId' : IDL.Nat,
  'temperature' : IDL.Float64,
  'createdAt' : Timestamp,
  'spo2' : IDL.Nat,
  'visitType' : IDL.Text,
  'reviewedBy' : UserId,
  'glucose' : IDL.Nat,
  'volunteerId' : UserId,
  'checkDate' : IDL.Text,
  'heartRate' : IDL.Nat,
  'doctorAdvice' : IDL.Text,
  'symptoms' : IDL.Text,
  'bpDiastolic' : IDL.Nat,
  'reviewed' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [Patient],
      [],
    ),
  'createRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Record({ 'alerts' : IDL.Vec(Alert), 'record' : HealthRecord })],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [User], []),
  'getAlerts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'alert' : Alert,
            'village' : IDL.Text,
            'patientCode' : IDL.Text,
            'patientName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getPatient' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'patient' : Patient,
            'volunteerName' : IDL.Text,
            'records' : IDL.Vec(HealthRecord),
          })
        ),
      ],
      ['query'],
    ),
  'getPatients' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'patient' : Patient,
            'volunteerName' : IDL.Text,
            'lastCheck' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getRecords' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Nat)],
      [
        IDL.Vec(
          IDL.Record({
            'village' : IDL.Text,
            'patientCode' : IDL.Text,
            'patientName' : IDL.Text,
            'record' : HealthRecord,
          })
        ),
      ],
      ['query'],
    ),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingReview' : IDL.Nat,
          'totalPatients' : IDL.Nat,
          'activeVolunteers' : IDL.Nat,
          'recordsToday' : IDL.Nat,
          'activeAlerts' : IDL.Nat,
          'totalRecords' : IDL.Nat,
          'alertPatients' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getVolunteers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [User], []),
  'resolveAlert' : IDL.Func([IDL.Nat], [IDL.Opt(Alert)], []),
  'reviewRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(HealthRecord)], []),
  'seedDemoData' : IDL.Func([], [IDL.Text], []),
  'updatePatient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Patient)],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [IDL.Opt(User)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const UserId = IDL.Nat;
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'volunteerId' : UserId,
    'address' : IDL.Text,
    'village' : IDL.Text,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'patientCode' : IDL.Text,
    'phone' : IDL.Text,
    'condition' : IDL.Text,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'alertType' : IDL.Text,
    'patientId' : IDL.Nat,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'recordId' : IDL.Nat,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Nat,
    'bpSystolic' : IDL.Nat,
    'patientId' : IDL.Nat,
    'temperature' : IDL.Float64,
    'createdAt' : Timestamp,
    'spo2' : IDL.Nat,
    'visitType' : IDL.Text,
    'reviewedBy' : UserId,
    'glucose' : IDL.Nat,
    'volunteerId' : UserId,
    'checkDate' : IDL.Text,
    'heartRate' : IDL.Nat,
    'doctorAdvice' : IDL.Text,
    'symptoms' : IDL.Text,
    'bpDiastolic' : IDL.Nat,
    'reviewed' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'createPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [Patient],
        [],
      ),
    'createRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Record({ 'alerts' : IDL.Vec(Alert), 'record' : HealthRecord })],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [User], []),
    'getAlerts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'alert' : Alert,
              'village' : IDL.Text,
              'patientCode' : IDL.Text,
              'patientName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getPatient' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'patient' : Patient,
              'volunteerName' : IDL.Text,
              'records' : IDL.Vec(HealthRecord),
            })
          ),
        ],
        ['query'],
      ),
    'getPatients' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'patient' : Patient,
              'volunteerName' : IDL.Text,
              'lastCheck' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getRecords' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Nat)],
        [
          IDL.Vec(
            IDL.Record({
              'village' : IDL.Text,
              'patientCode' : IDL.Text,
              'patientName' : IDL.Text,
              'record' : HealthRecord,
            })
          ),
        ],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingReview' : IDL.Nat,
            'totalPatients' : IDL.Nat,
            'activeVolunteers' : IDL.Nat,
            'recordsToday' : IDL.Nat,
            'activeAlerts' : IDL.Nat,
            'totalRecords' : IDL.Nat,
            'alertPatients' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getVolunteers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [User], []),
    'resolveAlert' : IDL.Func([IDL.Nat], [IDL.Opt(Alert)], []),
    'reviewRecord' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(HealthRecord)], []),
    'seedDemoData' : IDL.Func([], [IDL.Text], []),
    'updatePatient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Patient)],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [IDL.Opt(User)], []),
  });
};

export const init = ({ IDL }) => { return []; };