/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = bigint;
export type Timestamp = bigint;
export interface User {
    id: UserId;
    principal: Principal;
    patientId?: bigint;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface HealthRecord {
    id: bigint;
    bpSystolic: bigint;
    patientId: bigint;
    temperature: number;
    createdAt: Timestamp;
    spo2: bigint;
    visitType: string;
    reviewedBy: UserId;
    glucose: bigint;
    volunteerId: UserId;
    checkDate: string;
    heartRate: bigint;
    doctorAdvice: string;
    symptoms: string;
    bpDiastolic: bigint;
    reviewed: boolean;
}
export interface Alert {
    id: bigint;
    resolved: boolean;
    alertType: string;
    patientId: bigint;
    createdAt: Timestamp;
    message: string;
    recordId: bigint;
}
export interface Patient {
    id: bigint;
    age: bigint;
    status: string;
    name: string;
    createdAt: Timestamp;
    volunteerId: UserId;
    address: string;
    village: string;
    gender: string;
    notes: string;
    patientCode: string;
    phone: string;
    condition: string;
}
export enum UserRole {
    patient = "patient",
    admin = "admin",
    doctor = "doctor",
    visitor = "visitor",
    volunteer = "volunteer"
}
export interface backendInterface {
    createPatient(name: string, age: bigint, gender: string, phone: string, village: string, address: string, condition: string, volunteerId: bigint, notes: string): Promise<Patient>;
    createRecord(patientId: bigint, visitType: string, bpSystolic: bigint, bpDiastolic: bigint, glucose: bigint, heartRate: bigint, spo2: bigint, temperature: number, symptoms: string, checkDate: string): Promise<{
        alerts: Array<Alert>;
        record: HealthRecord;
    }>;
    createUser(name: string, email: string, role: UserRole): Promise<User>;
    getAlerts(): Promise<Array<{
        alert: Alert;
        village: string;
        patientCode: string;
        patientName: string;
    }>>;
    getCurrentUser(): Promise<User | null>;
    getMyAlerts(): Promise<Array<{
        alert: Alert;
        village: string;
        patientCode: string;
        patientName: string;
    }>>;
    getMyRecord(): Promise<{
        patient: Patient;
        volunteerName: string;
        records: Array<HealthRecord>;
    } | null>;
    getPatient(id: bigint): Promise<{
        patient: Patient;
        volunteerName: string;
        records: Array<HealthRecord>;
    } | null>;
    getPatients(): Promise<Array<{
        patient: Patient;
        volunteerName: string;
        lastCheck?: string;
    }>>;
    getRecords(reviewed: boolean | null, patientId: bigint | null): Promise<Array<{
        village: string;
        patientCode: string;
        patientName: string;
        record: HealthRecord;
    }>>;
    getStats(): Promise<{
        pendingReview: bigint;
        totalPatients: bigint;
        activeVolunteers: bigint;
        recordsToday: bigint;
        activeAlerts: bigint;
        totalRecords: bigint;
        alertPatients: bigint;
    }>;
    getUsers(): Promise<Array<User>>;
    getVolunteers(): Promise<Array<User>>;
    linkPatientAccount(userId: bigint, patientId: bigint): Promise<User | null>;
    registerUser(name: string, email: string, role: UserRole): Promise<User>;
    resolveAlert(alertId: bigint): Promise<Alert | null>;
    reviewRecord(recordId: bigint, advice: string): Promise<HealthRecord | null>;
    seedDemoData(): Promise<string>;
    updatePatient(id: bigint, condition: string, status: string, notes: string): Promise<Patient | null>;
    updateUserRole(userId: bigint, role: UserRole): Promise<User | null>;
}
import type { Alert as _Alert, HealthRecord as _HealthRecord, Patient as _Patient, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPatient(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createRecord(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: number, arg8: string, arg9: string): Promise<{
        alerts: Array<Alert>;
        record: HealthRecord;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: UserRole): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlerts(): Promise<Array<{
        alert: Alert;
        village: string;
        patientCode: string;
        patientName: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return result;
        }
    }
    async getCurrentUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAlerts(): Promise<Array<{
        alert: Alert;
        village: string;
        patientCode: string;
        patientName: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAlerts();
            return result;
        }
    }
    async getMyRecord(): Promise<{
        patient: Patient;
        volunteerName: string;
        records: Array<HealthRecord>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecord();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecord();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: bigint): Promise<{
        patient: Patient;
        volunteerName: string;
        records: Array<HealthRecord>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatients(): Promise<Array<{
        patient: Patient;
        volunteerName: string;
        lastCheck?: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatients();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatients();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecords(arg0: boolean | null, arg1: bigint | null): Promise<Array<{
        village: string;
        patientCode: string;
        patientName: string;
        record: HealthRecord;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecords(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecords(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getStats(): Promise<{
        pendingReview: bigint;
        totalPatients: bigint;
        activeVolunteers: bigint;
        recordsToday: bigint;
        activeAlerts: bigint;
        totalRecords: bigint;
        alertPatients: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async linkPatientAccount(arg0: bigint, arg1: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.linkPatientAccount(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkPatientAccount(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: UserRole): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveAlert(arg0: bigint): Promise<Alert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async reviewRecord(arg0: bigint, arg1: string): Promise<HealthRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewRecord(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewRecord(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedDemoData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1, arg2, arg3);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1, arg2, arg3);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: bigint, arg1: UserRole): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_User_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Alert]): Alert | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthRecord]): HealthRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        patient: _Patient;
        volunteerName: string;
        records: Array<_HealthRecord>;
    }]): {
    patient: Patient;
    volunteerName: string;
    records: Array<HealthRecord>;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: _Patient;
    volunteerName: string;
    lastCheck: [] | [string];
}): {
    patient: Patient;
    volunteerName: string;
    lastCheck?: string;
} {
    return {
        patient: value.patient,
        volunteerName: value.volunteerName,
        lastCheck: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastCheck))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    principal: Principal;
    patientId: [] | [bigint];
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    id: UserId;
    principal: Principal;
    patientId?: bigint;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        patientId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.patientId)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} | {
    visitor: null;
} | {
    volunteer: null;
}): UserRole {
    return "patient" in value ? UserRole.patient : "admin" in value ? UserRole.admin : "doctor" in value ? UserRole.doctor : "visitor" in value ? UserRole.visitor : "volunteer" in value ? UserRole.volunteer : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    patient: _Patient;
    volunteerName: string;
    lastCheck: [] | [string];
}>): Array<{
    patient: Patient;
    volunteerName: string;
    lastCheck?: string;
}> {
    return value.map((x)=>from_candid_record_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n3(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} | {
    visitor: null;
} | {
    volunteer: null;
} {
    return value == UserRole.patient ? {
        patient: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.doctor ? {
        doctor: null
    } : value == UserRole.visitor ? {
        visitor: null
    } : value == UserRole.volunteer ? {
        volunteer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
